### PR TITLE
Update for Confluent.Kafka 1.0-beta2

### PR DESCRIPTION
**Pull request by kronscht**

### CODE REVIEW

**Comment by hayrullahcansu** [comment]
Thanks for the commits. I will do test and publish to nuget.

**Comment by hayrullahcansu** [comment]
Why did you change to closed the PR?

**Comment by hayrullahcansu** [comment]
Why did you change to closed the PR?

**Comment by kronscht** [comment]
Hi Hayrullah cansu,

sorry for the confusion. I thought the master branch is my personal master branch after the fork.
I haven’t seen that I was merging back to your master branch while creating the pull request.

So I canceled the PR.

Greetings,
Tobias Kronschnabl

Von: Hayrullah cansu <notifications@github.com>
Gesendet: Montag, 22. Oktober 2018 12:44
An: hayrullahcansu/log4net-kafka-appender <log4net-kafka-appender@noreply.github.com>
Cc: Tobias Kronschnabl <Tobias.Kronschnabl@msg-gillardon.de>; State change <state_change@noreply.github.com>
Betreff: Re: [hayrullahcansu/log4net-kafka-appender] Update for Confluent.Kafka 1.0-beta2 (#2)


Why did you change to closed the PR?

**Comment by hayrullahcansu** [comment]
Okay, no problem about that. Feel free to create PR to improve the project on nuget.

**Pull request closed without merging**
